heat_template_version: 2014-10-16

parameters:
  keypair:
    type: string
    description: Name of a KeyPair

resources:
  my_server:
    type: https://raw.githubusercontent.com/olguncengiz/test/master/testserver1.yaml
    properties:
      keyname: {get_param: keypair}
