heat_template_version: 2014-10-16

parameters:
  keyname:
    type: string
    description: Name of a KeyPair

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: TestServer1
      key_name: {get_param: keyname}
      flavor: m1.compact
      networks: [{network: net04 }]
      image: Centos 6.5 x64 (pre installed node.js stack)
      
outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }
